-- AlterTable
ALTER TABLE "Betta" ALTER COLUMN "river" DROP NOT NULL,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "province" DROP NOT NULL,
ALTER COLUMN "ph_water" DROP NOT NULL,
ALTER COLUMN "complex_slug" DROP NOT NULL;
