import z from "zod";

export const betta = z.object({
  name: z.string().openapi({
    example: "betta hendra",
    minimum: 3,
    maximum: 100,
  }),
  slug: z.string().openapi({
    example: "betta-hendra",
  }),
  river: z.string().nullable().optional().openapi({
    example: "sabangau",
    minimum: 3,
    maximum: 100,
  }),
  city: z.string().nullable().optional().openapi({
    example: "katingan",
    minimum: 3,
    maximum: 100,
  }),
  province: z.string().nullable().optional().openapi({
    example: "central kalimantan",
    minimum: 3,
    maximum: 100,
  }),
  ph_water: z.string().nullable().optional().openapi({
    example: "4.0 - 6.5",
    minimum: 3,
    maximum: 100,
  }),
  complex_slug: z.string().nullable().optional().openapi({
    example: "coccina",
    minimum: 3,
    maximum: 100,
  }),
  category: z.string().openapi({
    example: "bubble nester small",
    minimum: 3,
    maximum: 100,
  }),
});

export const getBettaBySlug = betta.pick({
  slug: true,
});

export const getBettaByID = z.object({
  id: z.number(),
});

export type Betta = z.infer<typeof betta>;
export type Bettas = Betta[];

export const dataBettas: Bettas = [
  {
    name: "betta compuncta",
    slug: "betta-compuncta",
    river: null,
    city: null,
    province: "east kalimantan",
    ph_water: "3.7 - 5.3",
    complex_slug: "unimaculata",
    category: "mouth brooder large",
  },
  {
    name: "betta galdiator",
    slug: "betta-galdiator",
    river: null,
    city: null,
    province: "kalimantan",
    ph_water: "4.2 - 4.8",
    complex_slug: "unimaculata",
    category: "mouth brooder large",
  },
  {
    name: "betta ideii",
    slug: "betta-ideii",
    river: null,
    city: null,
    province: "south kalimantan",
    ph_water: "5.5 - 7.5",
    complex_slug: "unimaculata",
    category: "mouth brooder large",
  },
  {
    name: "betta pallifina",
    slug: "betta-pallifina",
    river: "barito river",
    city: null,
    province: "central kalimantan",
    ph_water: "6.6 - 7.4.",
    complex_slug: "unimaculata",
    category: "mouth brooder large",
  },
  {
    name: "betta patoti",
    slug: "betta-patoti",
    river: "mangar",
    city: "balikpapan",
    province: "east kalimantan",
    ph_water: "4.0 - 7.0",
    complex_slug: "unimaculata",
    category: "mouth brooder large",
  },
  {
    name: "betta unimaculata",
    slug: "betta-unimaculata",
    river: "kajan",
    city: null,
    province: "east kalimantan",
    ph_water: "5.0 - 7.5",
    complex_slug: "unimaculata",
    category: "mouth brooder large",
  },
  {
    name: "betta antuta",
    slug: "betta-antuta",
    river: null,
    city: "bulunga",
    province: "east kalimantan",
    ph_water: null,
    complex_slug: "unimaculata",
    category: "mouth brooder large",
  },
  {
    name: "betta chlorapharynx",
    slug: "betta-chlorapharynx",
    river: null,
    city: "bangka belitung",
    province: "east sumatra",
    ph_water: "3.0 - 4.0.",
    complex_slug: "waseri",
    category: "mouth brooder large",
  },
  {
    name: "betta hipposysderos",
    slug: "betta-hipposysderos",
    river: null,
    city: null,
    province: "riau",
    ph_water: "3.5 - 6.0",
    complex_slug: "waseri",
    category: "mouth brooder large",
  },
  {
    name: "betta pardalotos",
    slug: "betta-pardalotos",
    river: "galem",
    city: "palembang",
    province: "south sumatra",
    ph_water: "4.0 - 6.5",
    complex_slug: "waseri",
    category: "mouth brooder large",
  },
  {
    name: "betta renata",
    slug: "betta-renata",
    river: null,
    city: "jambi",
    province: "jambi",
    ph_water: "3.0 or 4.0",
    complex_slug: "waseri",
    category: "mouth brooder large",
  },
  {
    name: "betta spilotogena",
    slug: "betta-spilotogena",
    river: null,
    city: "bintan",
    province: "riau",
    ph_water: "4.9 - 5.5",
    complex_slug: "waseri",
    category: "mouth brooder large",
  },
  {
    name: "betta channoides",
    slug: "betta-channoides",
    river: "Sungai Mahakam",
    city: "Pampang",
    province: "East Kalimantan",
    ph_water: "4.0 - 6.5",
    complex_slug: null,
    category: "mouth brooder small",
  },
  {
    name: "betta albimarginata",
    slug: "betta-albimarginata",
    river: "Sebuku",
    city: "nunukan",
    province: "East Kalimantan",
    ph_water: "4.0 - 6.0",
    complex_slug: null,
    category: "mouth brooder small",
  },
  {
    name: "betta hendra",
    slug: "betta-hendra",
    river: "Sabangau",
    city: "katingan",
    province: "central kalimantan",
    ph_water: "4.0 - 6.5",
    complex_slug: "coccina",
    category: "bubble nester small",
  },
  {
    name: "betta brownorum",
    slug: "betta-brownorum",
    river: null,
    city: null,
    province: "kalimantan",
    ph_water: "4.0 - 6.5",
    complex_slug: "coccina",
    category: "bubble nester small",
  },
  {
    name: "betta burdigala",
    slug: "betta-burdigala",
    river: null,
    city: "bangka island",
    province: "east sumatra",
    ph_water: "4.0 - 6.0",
    complex_slug: "coccina",
    category: "bubble nester small",
  },
  {
    name: "betta coccina",
    slug: "betta-coccina",
    river: null,
    city: null,
    province: "sumatra",
    ph_water: " 3.5 - 4.5",
    complex_slug: "coccina",
    category: "bubble nester small",
  },
  {
    name: "betta miniopinna",
    slug: "betta-miniopinna",
    river: null,
    city: "bangka island",
    province: "riau",
    ph_water: "4.0 - 6.5",
    complex_slug: "coccina",
    category: "bubble nester small",
  },
  {
    name: "betta rutilans",
    slug: "betta-rutilans",
    river: "mempawah",
    city: "anjungan",
    province: "west kalimantan",
    ph_water: "3.0 - 6.0",
    complex_slug: "coccina",
    category: "bubble nester small",
  },
  {
    name: "betta uberis",
    slug: "betta-uberis",
    river: "kumai",
    city: "pangkalan bun",
    province: "central kalimantan",
    ph_water: "4.0 - 6.0",
    complex_slug: "coccina",
    category: "bubble nester small",
  },
  {
    name: "betta Bellica",
    slug: "betta-bellica",
    river: null,
    city: null,
    province: "East Sumatra",
    ph_water: "4,0 - 6,5",
    complex_slug: null,
    category: "bubble nester large",
  },
  {
    name: "betta Simorum",
    slug: "betta-simorum",
    river: "Kapuas",
    city: "Jambi",
    province: "west Kalimantan",
    ph_water: "4,0 - 6,5",
    complex_slug: null,
    category: "bubble nester large",
  },
];
