import { Bettas } from "./schema";

export const bettas: Bettas = [
  {
    name: "betta compuncta",
    slug: "betta-compuncta",
    river: null,
    city: null,
    province: "east-kalimantan",
    phWater: "3.7 - 5.3",
    complexSlug: "unimaculata",
    categorySlug: "mouth brooder large",
  },
  {
    name: "betta galdiator",
    slug: "betta-galdiator",
    river: null,
    city: null,
    province: "kalimantan",
    phWater: "4.2 - 4.8",
    complexSlug: "unimaculata",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta ideii",
    slug: "betta-ideii",
    river: null,
    city: null,
    province: "south-kalimantan",
    phWater: "5.5 - 7.5",
    complexSlug: "unimaculata",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta pallifina",
    slug: "betta-pallifina",
    river: "barito-river",
    city: null,
    province: "central-kalimantan",
    phWater: "6.6 - 7.4",
    complexSlug: "unimaculata",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta patoti",
    slug: "betta-patoti",
    river: "mangar",
    city: "balikpapan",
    province: "east-kalimantan",
    phWater: "4.0 - 7.0",
    complexSlug: "unimaculata",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta unimaculata",
    slug: "betta-unimaculata",
    river: "kajan",
    city: null,
    province: "east-kalimantan",
    phWater: "5.0 - 7.5",
    complexSlug: "unimaculata",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta antuta",
    slug: "betta-antuta",
    river: null,
    city: "bulunga",
    province: "east-kalimantan",
    phWater: null,
    complexSlug: "unimaculata",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta chlorapharynx",
    slug: "betta-chlorapharynx",
    river: null,
    city: "bangka-belitung",
    province: "east-sumatra",
    phWater: "3.0 - 4.0",
    complexSlug: "waseri",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta hipposysderos",
    slug: "betta-hipposysderos",
    river: null,
    city: null,
    province: "riau",
    phWater: "3.5 - 6.0",
    complexSlug: "waseri",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta pardalotos",
    slug: "betta-pardalotos",
    river: "galem",
    city: "palembang",
    province: "south-sumatra",
    phWater: "4.0 - 6.5",
    complexSlug: "waseri",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta renata",
    slug: "betta-renata",
    river: null,
    city: "jambi",
    province: "jambi",
    phWater: "3.0 - 4.0",
    complexSlug: "waseri",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta spilotogena",
    slug: "betta-spilotogena",
    river: null,
    city: "bintan",
    province: "riau",
    phWater: "4.9 - 5.5",
    complexSlug: "waseri",
    categorySlug: "mouth-brooder-large",
  },
  {
    name: "betta channoides",
    slug: "betta-channoides",
    river: "sungai-mahakam",
    city: "pampang",
    province: "east-kalimantan",
    phWater: "4.0 - 6.5",
    complexSlug: null,
    categorySlug: "mouth-brooder-small",
  },
  {
    name: "betta albimarginata",
    slug: "betta-albimarginata",
    river: "sebuku",
    city: "nunukan",
    province: "east-kalimantan",
    phWater: "4.0 - 6.0",
    complexSlug: null,
    categorySlug: "mouth-brooder-small",
  },
  {
    name: "betta hendra",
    slug: "betta-hendra",
    river: "sabangau",
    city: "katingan",
    province: "central-kalimantan",
    phWater: "4.0 - 6.5",
    complexSlug: "coccina",
    categorySlug: "bubble-nester-small",
  },
  {
    name: "betta brownorum",
    slug: "betta-brownorum",
    river: null,
    city: null,
    province: "kalimantan",
    phWater: "4.0 - 6.5",
    complexSlug: "coccina",
    categorySlug: "bubble-nester-small",
  },
  {
    name: "betta burdigala",
    slug: "betta-burdigala",
    river: null,
    city: "bangka-island",
    province: "east-sumatra",
    phWater: "4.0 - 6.0",
    complexSlug: "coccina",
    categorySlug: "bubble-nester-small",
  },
  {
    name: "betta coccina",
    slug: "betta-coccina",
    river: null,
    city: null,
    province: "sumatra",
    phWater: "3.5 - 4.5",
    complexSlug: "coccina",
    categorySlug: "bubble-nester-small",
  },
  {
    name: "betta miniopinna",
    slug: "betta-miniopinna",
    river: null,
    city: "bangka-island",
    province: "riau",
    phWater: "4.0 - 6.5",
    complexSlug: "coccina",
    categorySlug: "bubble-nester-small",
  },
  {
    name: "betta rutilans",
    slug: "betta-rutilans",
    river: "mempawah",
    city: "anjungan",
    province: "west-kalimantan",
    phWater: "3.0 - 6.0",
    complexSlug: "coccina",
    categorySlug: "bubble-nester-small",
  },
  {
    name: "betta uberis",
    slug: "betta-uberis",
    river: "kumai",
    city: "pangkalan-bun",
    province: "central-kalimantan",
    phWater: "4.0 - 6.0",
    complexSlug: "coccina",
    categorySlug: "bubble-nester-small",
  },
  {
    name: "betta Bellica",
    slug: "betta-bellica",
    river: null,
    city: null,
    province: "east-sumatra",
    phWater: "4.0 - 6.5",
    complexSlug: null,
    categorySlug: "bubble-nester-large",
  },
  {
    name: "betta Simorum",
    slug: "betta-simorum",
    river: "kapuas",
    city: "jambi",
    province: "west-kalimantan",
    phWater: "4.0 - 6.5",
    complexSlug: null,
    categorySlug: "bubble-nester-large",
  },
];
