import { randomUUIDv7 } from "bun";
import { type Bettas } from "../type/schema";

export let wildBettas: Bettas = [
  {
    id: randomUUIDv7(),
    name: "Betta Channoides",
    slug: "betta-channoides",
    location: {
      river: "Sungai Mahakam",
      city: "Pampang",
      province: "East Kalimantan",
    },
    phWater: "4,0-6,5",
    complex: null,
    category: "Mouth Brooder Small",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: randomUUIDv7(),
    name: "Betta Albimarginata",
    slug: "betta-albimarginata",
    location: { river: "Sebuku", city: "nunukan", province: "East Kalimantan" },
    phWater: "4,0-6,0",
    complex: null,
    category: "Mouth Brooder Large",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: randomUUIDv7(),
    name: "Betta Hendra",
    slug: "betta-hendra",
    location: { river: "Sabangau", city: null, province: "Central Kalimantan" },
    phWater: "4,0 - 6,5",
    complex: "coccina",
    category: "Bubble Nester Small",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: randomUUIDv7(),
    name: "Betta brownorum",
    slug: "betta-brownorum",
    location: { river: null, city: null, province: "Kalimantan" },
    phWater: "4,0 - 6,5",
    complex: "coccina",
    category: "Bubble Nester Small",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: randomUUIDv7(),
    name: "Betta Bellica",
    slug: "betta-bellica",
    location: { river: null, city: null, province: "East Sumatra" },
    phWater: "4,0 - 6,5",
    complex: null,
    category: "Bubble Nester Large",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: randomUUIDv7(),
    name: "Betta Simorum",
    slug: "betta-simorum",
    location: { river: "Kapuas", city: "Jambi", province: "west Kalimantan" },
    phWater: "4,0 - 6,5",
    complex: null,
    category: "Bubble Nester Large",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: randomUUIDv7(),
    name: "Betta Antuta",
    slug: "betta-antuta",
    location: { river: null, city: "Bulungan", province: "East Kalimantan" },
    phWater: "4,0 - 6,5",
    complex: null,
    category: "Mouth Brooder Large",
    createdAt: new Date(),
    updateAt: new Date(),
  },
  {
    id: randomUUIDv7(),
    name: "Betta Renata",
    slug: "betta-renata",
    location: {
      river: "Indragiri Basin",
      city: "Jambi",
      province: "South Sumatra",
    },
    phWater: "4,0 - 6,5",
    complex: null,
    category: "Bubble Nester Small",
    createdAt: new Date(),
    updateAt: new Date(),
  },
];
